name: Validate and lint
on: [ push ]
jobs:
  terraform-checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        provider: [ backblaze, cloudflare, oracle_cloud, scaleway, tebi ]
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
      - name: Show terraform version
        run: terraform version
      - name: Initialize terraform
        run: terraform init
        working-directory: providers/${{ matrix.provider }}
      - name: Validate terraform code
        run: terraform validate
        working-directory: providers/${{ matrix.provider }}
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: "latest"
      - name: Show tflint version
        run: tflint --version
      - name: Run tflint
        run: tflint --recursive
        working-directory: providers/${{ matrix.provider }}
